version: "3.9"
services:
  app:
    depends_on:
      postgres:
        condition: service_healthy
    image: svhd/logto:${TAG-latest}
    entrypoint: ["sh", "-c", "npm run cli db seed -- --swe && npm start"]
    ports:
      - "3001:3001"
      - "3002:3002"
    environment:
      - TRUST_PROXY_HEADER=1
      - DB_URL=${DB_URL}  # La variable sera injectée via Coolify
      - ENDPOINT=${ENDPOINT}  # URL publique de l'application
      - ADMIN_ENDPOINT=${ADMIN_ENDPOINT}  # URL publique de l'admin
